In [21]:
import pandas as pd
data = pd.read_csv('BL-Flickr-Images-Book.csv')
print(data)

      Identifier             Edition Statement      Place of Publication  \
0            206                           NaN                    London
1            216                           NaN  London; Virtue & Yorston
2            218                           NaN                    London
3            472                           NaN                    London
4            480  A new edition, revised, etc.                    London
...          ...                           ...                       ...
8282     4158088                           NaN                    London
8283     4158128                           NaN                     Derby
8284     4159563                           NaN                    London
8285     4159587                           NaN       Newcastle upon Tyne
8286     4160339                           NaN                    London

     Date of Publication                Publisher  \
0            1879 [1878]         S. Tinsley & Co.
1                   1868             Virtue & Co.
2                   1869    Bradbury, Evans & Co.
3                   1851            James Darling
4                   1857     Wertheim & Macintosh
...                  ...                      ...
8282                1838                      NaN
8283            1831, 32          M. Mozley & Son
8284           [1806]-22  T. Cadell and W. Davies
8285                1834         Mackenzie & Dent
8286             1834-43                      NaN

                                                  Title  \
0                     Walter Forbes. [A novel.] By A. A
1     All for Greed. [A novel. The dedication signed...
2     Love the Avenger. By the author of â€œAll for Gr...
3     Welsh Sketches, chiefly ecclesiastical, to the...
4     [The World in which I live, and my place in it...
...                                                 ...
8282  The Parochial History of Cornwall, founded on,...
8283  The History and Gazetteer of the County of Der...
8284  Magna Britannia; being a concise topographical...
8285  An historical, topographical and descriptive v...
8286  Collectanea Topographica et Genealogica. [Firs...

                                                 Author  \
0                                                 A. A.
1                                             A., A. A.
2                                             A., A. A.
3                                             A., E. S.
4                                             A., E. S.
...                                                 ...
8282                 GIDDY, afterwards GILBERT, Davies.
8283                         GLOVER, Stephen - of Derby
8284  LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...
8285                              Mackenzie, E. (Eneas)
8286                                                NaN

                                           Contributors  Corporate Author  \
0                                       FORBES, Walter.               NaN
1          BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
2          BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
3                           Appleyard, Ernest Silvanus.               NaN
4                                   BROOME, John Henry.               NaN
...                                                 ...               ...
8282  BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...               NaN
8283                                     NOBLE, Thomas.               NaN
8284           GREGSON, Matthew.|LYSONS, Samuel - F.R.S               NaN
8285                               ROSS, M. - of Durham               NaN
8286            BANDINEL, Bulkeley.|Nichols, John Gough               NaN

      Corporate Contributors Former owner  Engraver Issuance type  \
0                        NaN          NaN       NaN   monographic
1                        NaN          NaN       NaN   monographic
2                        NaN          NaN       NaN   monographic
3                        NaN          NaN       NaN   monographic
4                        NaN          NaN       NaN   monographic
...                      ...          ...       ...           ...
8282                     NaN          NaN       NaN   monographic
8283                     NaN          NaN       NaN   monographic
8284                     NaN          NaN       NaN   monographic
8285                     NaN          NaN       NaN   monographic
8286                     NaN          NaN       NaN    continuing

                                             Flickr URL  \
0     http://www.flickr.com/photos/britishlibrary/ta...
1     http://www.flickr.com/photos/britishlibrary/ta...
2     http://www.flickr.com/photos/britishlibrary/ta...
3     http://www.flickr.com/photos/britishlibrary/ta...
4     http://www.flickr.com/photos/britishlibrary/ta...
...                                                 ...
8282  http://www.flickr.com/photos/britishlibrary/ta...
8283  http://www.flickr.com/photos/britishlibrary/ta...
8284  http://www.flickr.com/photos/britishlibrary/ta...
8285  http://www.flickr.com/photos/britishlibrary/ta...
8286  http://www.flickr.com/photos/britishlibrary/ta...

                                             Shelfmarks
0                     British Library HMNTS 12641.b.30.
1                     British Library HMNTS 12626.cc.2.
2                     British Library HMNTS 12625.dd.1.
3                   British Library HMNTS 10369.bbb.15.
4                      British Library HMNTS 9007.d.28.
...                                                 ...
8282  British Library HMNTS|British Library HMNTS 10...
8283  British Library HMNTS|British Library HMNTS 10...
8284  British Library HMNTS|British Library HMNTS 19...
8285  British Library HMNTS|British Library HMNTS 10...
8286  British Library HMNTS|British Library HMNTS 79...

[8287 rows x 15 columns]

In [3]:

                                            ### Exploring the dataset ###
    
data.head()   # this will display the first few rows of dara

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [4]:

data.describe() # basic statistics
# data['Identifier'].is_unique
data.set_index('Identifier', inplace=True)
data.loc[206]

Edition Statement                                                       NaN
Place of Publication                                                 London
Date of Publication                                             1879 [1878]
Publisher                                                  S. Tinsley & Co.
Title                                     Walter Forbes. [A novel.] By A. A
Author                                                                A. A.
Contributors                                                FORBES, Walter.
Corporate Author                                                        NaN
Corporate Contributors                                                  NaN
Former owner                                                            NaN
Engraver                                                                NaN
Issuance type                                                   monographic
Flickr URL                http://www.flickr.com/photos/britishlibrary/ta...
Shelfmarks                                British Library HMNTS 12641.b.30.
Name: 206, dtype: object

In [5]:

print(data.dtypes) # prints the type of data

Edition Statement          object
Place of Publication       object
Date of Publication        object
Publisher                  object
Title                      object
Author                     object
Contributors               object
Corporate Author          float64
Corporate Contributors    float64
Former owner               object
Engraver                  float64
Issuance type              object
Flickr URL                 object
Shelfmarks                 object
dtype: object

In [6]:
print(data.isnull().sum()) #number of missing values in each columns

Edition Statement         7514
Place of Publication         0
Date of Publication        181
Publisher                 4195
Title                        0
Author                    1778
Contributors                 0
Corporate Author          8287
Corporate Contributors    8287
Former owner              8286
Engraver                  8287
Issuance type                0
Flickr URL                   0
Shelfmarks                   0
dtype: int64

In [7]:

#                                         ###Handling the missing values###
#     ## this is the option A for dropping the value
# data = data.dropna()   # this will drop the row with missing values
# # # here i this the row with Summer will be dropped
# print(data)

In [8]:
regex = r'^(\d{4})'
data_num = data['Date of Publication'].str.extract(regex,expand=False)
data_num.head(15)

Identifier
206     1879
216     1868
218     1869
472     1851
480     1857
481     1875
519     1872
667      NaN
874     1676
1143    1679
1280    1802
1808    1859
1905    1888
1929    1839
2836    1897
Name: Date of Publication, dtype: object

In [9]:
data['Date of Publication'] = pd.to_numeric(data_num, downcast = 'integer')

In [10]:
data = data[data['Date of Publication'].isnull() != True]
data.head(15)

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,,,,,,,,
206,NaN,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
216,NaN,London; Virtue & Yorston,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
218,NaN,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
472,NaN,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
480,"A new edition, revised, etc.",London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
481,"Fourth edition, revised, etc.",London,1875.0,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9006.ee.10.
519,NaN,London,1872.0,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.","ASHLEY, Florence Emily.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12637.e.3.
874,NaN,London],1676.0,NaN,"A Warning to the inhabitants of England, and L...",RemaÊ¿.,"ADAMS, Mary.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11645.bb.42.
1143,NaN,London,1679.0,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.","OLDHAM, John.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11602.ee.10.(2.)
1280,NaN,Coventry,1802.0,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,"CARTE, Samuel.|JACKSON, Edward - Rector of Sou...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 1430.g.17.
1808,NaN,Christiania,1859.0,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.","AALL, J. C.|LANGE, Christian Christoph Andreas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9425.cc.37.
1905,NaN,Firenze,1888.0,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...","S., L. G. D.|SIMONE, Luigi Giuseppe Oronzo Mar...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10136.g.22.
1929,NaN,Amsterdam,1839.0,NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,"WITKAMP, Pieter Harme.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10002.g.16-19.
2836,NaN,Savona,1897.0,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.","ASSERETO, Giovanni.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10136.h.24.
2854,NaN,London,1865.0,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.","READE, William Winwood.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12623.bbb.12.

In [12]:
data_odx = [4157862,4159587]
data.loc[data_odx]

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,,,,,,,,
4157862,NaN,Newcastle-upon-Tyne,1867.0,T. Fordyce,"Local Records; or, Historical Register of rema...","FORDYCE, T. - Printer, of Newcastle-upon-Tyne","SYKES, John - Bookseller, of Newcastle-upon-Tyne",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 01...
4159587,NaN,Newcastle upon Tyne,1834.0,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...

In [19]:
import numpy as np

data['Place of Publication'] = np.where(data['Place of Publication'].str.contains('London'),'London',data['Place of Publication'].str.replace('-',' '))
data_odx = [4157862,4159587]
data.loc[data_odx]

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,,,,,,,,
4157862,NaN,Newcastle upon Tyne,1867.0,T. Fordyce,"Local Records; or, Historical Register of rema...","FORDYCE, T. - Printer, of Newcastle-upon-Tyne","SYKES, John - Bookseller, of Newcastle-upon-Tyne",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 01...
4159587,NaN,Newcastle upon Tyne,1834.0,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...

In [22]:
data.isnull().sum()

Identifier                   0
Edition Statement         7514
Place of Publication         0
Date of Publication        181
Publisher                 4195
Title                        0
Author                    1778
Contributors                 0
Corporate Author          8287
Corporate Contributors    8287
Former owner              8286
Engraver                  8287
Issuance type                0
Flickr URL                   0
Shelfmarks                   0
dtype: int64