In [23]:
import numpy as np
import pandas as pd

In [24]:
df_book=pd.read_csv("BL-Flickr-Images-Book.csv")
df_book.head(15)

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
5,481,"Fourth edition, revised, etc.",London,1875,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9006.ee.10.
6,519,NaN,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.","ASHLEY, Florence Emily.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12637.e.3.
7,667,NaN,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.","ANDREWS, J. - Writer of Verse",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 011652.g.73.
8,874,NaN,London],1676,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,"ADAMS, Mary.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11645.bb.42.
9,1143,NaN,London,1679,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.","OLDHAM, John.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11602.ee.10.(2.)
10,1280,NaN,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,"CARTE, Samuel.|JACKSON, Edward - Rector of Sou...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 1430.g.17.
11,1808,NaN,Christiania,1859,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.","AALL, J. C.|LANGE, Christian Christoph Andreas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9425.cc.37.
12,1905,NaN,Firenze,1888,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...","S., L. G. D.|SIMONE, Luigi Giuseppe Oronzo Mar...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10136.g.22.
13,1929,NaN,Amsterdam,"1839, 38-54",NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,"WITKAMP, Pieter Harme.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10002.g.16-19.
14,2836,NaN,Savona,1897,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.","ASSERETO, Giovanni.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10136.h.24.

In [25]:
df_book.shape

(8287, 15)

In [26]:
df_book.loc[0]

Identifier                                                              206
Edition Statement                                                       NaN
Place of Publication                                                 London
Date of Publication                                             1879 [1878]
Publisher                                                  S. Tinsley & Co.
Title                                     Walter Forbes. [A novel.] By A. A
Author                                                                A. A.
Contributors                                                FORBES, Walter.
Corporate Author                                                        NaN
Corporate Contributors                                                  NaN
Former owner                                                            NaN
Engraver                                                                NaN
Issuance type                                                   monographic
Flickr URL                http://www.flickr.com/photos/britishlibrary/ta...
Shelfmarks                                British Library HMNTS 12641.b.30.
Name: 0, dtype: object

In [27]:
to_drop=['Edition Statement','Corporate Author','Corporate',
'Contributors','Former owner','Engraver','Contributors','Issuance',
'type','Shelfmarks']
df_book.drop(columns=to_drop,inplace=True)
df_book.head(15)

KeyError: "['Corporate', 'Issuance', 'type'] not found in axis"

In [ ]:
df_book['Identifier'].is_unique

True

In [ ]:
df_book.set_index('Identifier',inplace=True)
df_book.loc[206]

Edition Statement                                                       NaN
Place of Publication                                                 London
Date of Publication                                             1879 [1878]
Publisher                                                  S. Tinsley & Co.
Title                                     Walter Forbes. [A novel.] By A. A
Author                                                                A. A.
Contributors                                                FORBES, Walter.
Corporate Author                                                        NaN
Corporate Contributors                                                  NaN
Former owner                                                            NaN
Engraver                                                                NaN
Issuance type                                                   monographic
Flickr URL                http://www.flickr.com/photos/britishlibrary/ta...
Shelfmarks                                British Library HMNTS 12641.b.30.
Name: 206, dtype: object

In [ ]:
df_book.dtypes.value_counts()
df_book.dtypes

Edition Statement          object
Place of Publication       object
Date of Publication        object
Publisher                  object
Title                      object
Author                     object
Contributors               object
Corporate Author          float64
Corporate Contributors    float64
Former owner               object
Engraver                  float64
Issuance type              object
Flickr URL                 object
Shelfmarks                 object
dtype: object

In [ ]:
df_book['Date of Publication'].head(15)

Identifier
206     1879 [1878]
216            1868
218            1869
472            1851
480            1857
481            1875
519            1872
667             NaN
874            1676
1143           1679
1280           1802
1808           1859
1905           1888
1929    1839, 38-54
2836           1897
Name: Date of Publication, dtype: object

In [ ]:
regex=r'^(\d{4})'
date_num=df_book['Date of Publication'].str.extract(regex,expand=False)
date_num.head(15)

Identifier
206     1879
216     1868
218     1869
472     1851
480     1857
481     1875
519     1872
667      NaN
874     1676
1143    1679
1280    1802
1808    1859
1905    1888
1929    1839
2836    1897
Name: Date of Publication, dtype: object

In [ ]:
df_book['Date of Publication']=pd.to_numeric(date_num,downcast='integer')
df_book['Date of Publication'].dtype

dtype('float64')

In [ ]:
df_book['Date of Publication'].isnull().sum()

971

In [ ]:
df_book['Date of Publication']=df_book['Date of Publication'].isnull().sum()!=True
df_book.head(15)

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,,,,,,,,
206,NaN,London,True,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
216,NaN,London; Virtue & Yorston,True,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
218,NaN,London,True,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
472,NaN,London,True,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
480,"A new edition, revised, etc.",London,True,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
481,"Fourth edition, revised, etc.",London,True,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9006.ee.10.
519,NaN,London,True,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.","ASHLEY, Florence Emily.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12637.e.3.
667,NaN,"pp. 40. G. Bryan & Co: Oxford, 1898",True,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.","ANDREWS, J. - Writer of Verse",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 011652.g.73.
874,NaN,London],True,NaN,"A Warning to the inhabitants of England, and L...",Remaʿ.,"ADAMS, Mary.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11645.bb.42.
1143,NaN,London,True,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.","OLDHAM, John.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11602.ee.10.(2.)
1280,NaN,Coventry,True,Printed by J. Turner,"An Account of the many and great Loans, Benefa...",NaN,"CARTE, Samuel.|JACKSON, Edward - Rector of Sou...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 1430.g.17.
1808,NaN,Christiania,True,NaN,Erindringer som Bidrag til Norges Historie fra...,"AALL, Jacob.","AALL, J. C.|LANGE, Christian Christoph Andreas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9425.cc.37.
1905,NaN,Firenze,True,NaN,Gli Studi storici in terra d'Otranto ... Framm...,"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oro...","S., L. G. D.|SIMONE, Luigi Giuseppe Oronzo Mar...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10136.g.22.
1929,NaN,Amsterdam,True,NaN,De Aardbol. Magazijn van hedendaagsche land- e...,NaN,"WITKAMP, Pieter Harme.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10002.g.16-19.
2836,NaN,Savona,True,NaN,Cronache Savonesi dal 1500 al 1570 ... Accresc...,"ABATE, Giovanni Agostino.","ASSERETO, Giovanni.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10136.h.24.

In [ ]:
book_idx=[4157862,4159587]
df_book.loc[book_idx]

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,,,,,,,,
4157862,NaN,Newcastle-upon-Tyne,True,T. Fordyce,"Local Records; or, Historical Register of rema...","FORDYCE, T. - Printer, of Newcastle-upon-Tyne","SYKES, John - Bookseller, of Newcastle-upon-Tyne",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 01...
4159587,NaN,Newcastle upon Tyne,True,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...

In [ ]:
df_book['Place of Publication']=np.where(df_book['Place of Publication'].str.contains('London'),'London',df_book['Place of Publication'].str.replace('-',' '))
book_idx=[216,4157862,4159587]
df_book.loc[book_idx]

,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
Identifier,,,,,,,,,,,,,,
216,NaN,London,True,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
4157862,NaN,Newcastle upon Tyne,True,T. Fordyce,"Local Records; or, Historical Register of rema...","FORDYCE, T. - Printer, of Newcastle-upon-Tyne","SYKES, John - Bookseller, of Newcastle-upon-Tyne",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 01...
4159587,NaN,Newcastle upon Tyne,True,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...

In [ ]:
null_counts=df_book.isnull().sum()
print(null_counts)

Edition Statement         7514
Place of Publication         0
Date of Publication          0
Publisher                 4195
Title                        0
Author                    1778
Contributors                 0
Corporate Author          8287
Corporate Contributors    8287
Former owner              8286
Engraver                  8287
Issuance type                0
Flickr URL                   0
Shelfmarks                   0
dtype: int64

In [ ]:
df_book['Author']=df_book['Author'].str.strip().str.title()
df_book['Author'].fillna('unknown',inplace=True)

In [ ]:
df_book['Publisher']=df_book['Publisher'].str.strip().str.title()
df_book['Publisher'].fillna(df_book["Place of Publication"],inplace=True)

In [ ]:
olympic_book=pd.read_csv("olympics.csv",header=1)
olympic_book.head(15)

In [ ]:
null_counts=olympic_book.isnull().sum()
print(null_counts)

In [ ]:
z_score=(olympic_book-olympic_book.mean())/olympic_book.std()
outliers_zscore=olympic_book[(z_score>3).any(axis=1)]
outliers_zscore

In [ ]:
olympic_book.drop(146)